### ISSUE TITLE
Error with the rotation of some animations 

### ISSUE THREAD

**Issue by MrSopaipilla** [Psycrow101/io_scene_gta_ifp#2]
Some animations such as walking or running, the character goes upwards instead of forwards, the same happens when exporting an animation.

**Comment by Psycrow101** [comment]
@Bastianhm22 What game? Can you share these animation files?

**Comment by MrSopaipilla** [comment]
It's in GTA SA, here are the files 

[ped.zip](https://github.com/Psycrow101/io_scene_gta_ifp/files/11226822/ped.zip)

**Comment by Psycrow101** [comment]
It looks like the direction of movement depends on the model itself. I added orientation options to control the direction.
https://github.com/Psycrow101/io_scene_gta_ifp/commit/9ac8a4a8968eb8a543a20a93d567a8c28b1ab4ae
![image](https://user-images.githubusercontent.com/31922454/232121624-1c974502-209a-4fc5-83f8-c09614d0a813.png)

**Comment by MrSopaipilla** [comment]
Woow thank you very much, now I can import those animations correctly
