### ISSUE TITLE
Problem when exporting an animation where the character moves from its position

### ISSUE THREAD

**Issue by MrSopaipilla** [Psycrow101/io_scene_gta_ifp#3]
There is a problem when an animation is exported where the character moves from its position, since when you put it in the game the character remains static, but if it plays the animation here is a video that explains it better

[https://www.youtube.com/watch?v=iC-3fMpQDBY](url)

**Comment by Psycrow101** [comment]
Is the issue still relevant? After importing back into Blender, does this behavior happen again?

**Comment by MrSopaipilla** [comment]
Hi yes, I really wish you could fix it, when I re-import the animation it doesn't move either, I think it's because the plugin doesn't export the skeleton or Root bone transformations.

**Comment by Psycrow101** [comment]
The plugin doesn't really export the armature transformation, but it does export bone keyframes, including the root bone. Can you share the .blend file for more details?

**Comment by MrSopaipilla** [comment]
Ah I see, but still the Root bone transformation is not exported, only the rotations are exported, that's something I saw, here I leave the .blend file 

[animation.zip](https://github.com/Psycrow101/io_scene_gta_ifp/files/12796904/animation.zip)

**Comment by Psycrow101** [comment]
It seems the bug was in the incorrect definition of the bone transformation type, which is why only the angles were exported. I fixed this issue in the latest update. Exporting animations should now work fine.

Thanks for feedback
