### ISSUE TITLE
cannot find the lists of animation inside IFP

### ISSUE THREAD

**Issue by SpeedyEastie** [Psycrow101/io_scene_gta_ifp#4]
i cannot find the animations that located inside the IFP.
Ex:i did import the "crack.ifp" and the ped only using laying down and when im trying to select the different animation but i cant find it.

btw,this tools supported the Blender 2.7+ and i see that is have lists of animations inside the IFPs, will the IO_scene_gta_ifp have or add/guide how to find it,hopefully i explain it properly and undertsand.
https://forum.gamerxserver.com/forum/samp-server-188-165-219-63-8800/questions-and-answers/tutorials/189333-blender-add-on-gta-tools

**Comment by Psycrow101** [comment]
Hello @SpeedyEastie

In Blender, animations are available in the Dope Sheet editor (Shift + F12). There you need to go to Action Editor. A list of actions will be available on the right.
![image](https://github.com/Psycrow101/io_scene_gta_ifp/assets/31922454/45bfbac4-223b-4d62-be19-69d6e323bad2)

If the animations are not in the list, then there may be an import error. In this case, please provide the files you tried to import.
